// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ILogger is an autogenerated mock type for the ILogger type
type ILogger struct {
	mock.Mock
}

// Log provides a mock function with given fields: accountId, failedCount
func (_m *ILogger) Log(accountId string, failedCount int) {
	_m.Called(accountId, failedCount)
}
