// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// INotification is an autogenerated mock type for the INotification type
type INotification struct {
	mock.Mock
}

// Notify provides a mock function with given fields: accountId
func (_m *INotification) Notify(accountId string) error {
	ret := _m.Called(accountId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(accountId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
